feat: internal heating
olegrog/awesumm pull request #39
Opened 2018-09-23 15:14 UTC by shmidt9510

2018-09-24 08:02 UTC, olegrog requested changes
Still wait when you are able to unite `laser_heat_source` and `laser_distribution`.

2018-09-24 08:02 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +  REAL(pr) :: optical_penetration_depth
1. We do not study optics. It is beyond our macroscopic model. We consider laser only as a directional heat source and we need not any information about the intensity of electromagnetic waves. `optical_penetration_depth` have nothing common with energy absorption. All light can be theoretically reflected.
2. We have already introduced `absorptivity` of laser energy. Note that we do not use words like `optical reflection` and so on, because it is all beyond our model. If we say about `absorptivity` of laser energy, it is logical to say about `absorption_length`, which is a [common term](https://en.wikipedia.org/wiki/Attenuation_length).

2018-09-24 08:02 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +    laser_heat_source = 2*laser_heat_flux(psi_prev)
`laser_heat_flux` can be excluded from this function since they are independent.

2018-09-24 08:21 UTC, shmidt9510 commented on slm_porosity/heat_transfer.f90
> +  REAL(pr) :: optical_penetration_depth
http://prntscr.com/kxyxgp
'Finite element simulation of selective laser melting process considering
optical penetration depth of laser in powder bed'

`Reflection` and `absorptivity` in reality is a parameter of bed which depends from temperature. `Absorptivity` gets closer to one when metal is liquid if I didn't miss anything. `Optical_penetration_depth` is a parameter from powder porosity and form and more close to the internal volume heating. 

Now I thought that `optical_penetration_depth` really didn't even requires study, cause we always light in the melted metal. 

If there is term `absorption_length` for water which also connected with Beer-Lambert law, I would agree on it.

2018-09-24 21:01 UTC, olegrog requested changes
Close to the final revision.

2018-09-24 21:01 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +  REAL(pr) :: absorption_length
Let it be `depth`.

2018-09-24 21:01 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +          laser_heat_flux(psi_prev)*laser_distribution(x, ng, dim, 3.0_pr)
1. Indentation.
2. What is `3.0_pr`?

2018-09-24 21:01 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +  LOGICAL  :: laser_as_bc
Let it be part of `boundary conditions` section.

2018-09-24 21:01 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +  PURE FUNCTION laser_distribution (x_, nlocal, dim_, factor)
Try to remove `factor` by yourself, because laser distribution just have not this parameter. This was my mistake in the past.

2018-09-24 21:01 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +    REAL(pr) :: FWHM(dim_)
I understand that you like `FWHM` very much, but let's avoid this term in this code.

2018-09-24 21:01 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +        gaussian(x_(:,i), x_center(i), FWHM(i), factor_)
I think we can use a single line here.

2018-09-24 21:01 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +  ELEMENTAL FUNCTION gaussian (coordinate, position, halfwidth, factor)
1. `(x, center, radius)`
2. Add a comment about what is the radius of gaussian.

2018-09-24 21:01 UTC, olegrog commented on slm_porosity/problem.inp
> +laser_as_bc = T                             # how the laser heat flux is implemented: T  - via BC, F -  via RHS.
Should the new feature be turned on?

2018-09-25 08:00 UTC, shmidt9510 commented on slm_porosity/heat_transfer.f90
> +  LOGICAL  :: laser_as_bc
As soon as additional flag PR would be merged

2018-09-25 08:04 UTC, shmidt9510 commented on slm_porosity/heat_transfer.f90
> +  PURE FUNCTION laser_distribution (x_, nlocal, dim_, factor)
`laser` have this parameter, but due to the fact I can't explain its physical meaning, I would delete it

2018-09-25 08:12 UTC, shmidt9510 commented on slm_porosity/heat_transfer.f90
> +  PURE FUNCTION laser_distribution (x_, nlocal, dim_, factor)
And you have it in IC. So I can't remove it in this PR

2018-09-25 08:49 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +  PURE FUNCTION laser_distribution (x_, nlocal, dim_, factor)
1. Check your comments after submitting.
2. Try to revise IC in this PR too.

2018-09-25 10:10 UTC, olegrog requested changes
Please, analyze every line that you write. Is it possible to write it in more simple and clear way?

2018-09-25 10:10 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +    ! radius*2*SQRT(2*log(2)) = sigma
1. Add comment before the signature of the function. 
2. It is not a comment, but copy-paste.`sigma` is excessive.
3. Simplify your expressions.

2018-09-25 10:10 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +  PURE FUNCTION laser_distribution (x_, nlocal, dim_, factor)
1. What about the first comment is?
2. Try to update IC as well in this PR.

2018-09-26 13:37 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +            laser_heat_flux(psi_prev)*laser_distribution(x, ng, dim)
`psi` instead of `psi_prev`

2018-09-26 13:38 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +    call input_logical('laser_as_bc', laser_as_bc, 'stop')
`! boundary conditions`

2018-09-26 13:39 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +    IF (.NOT.laser_as_bc) radius(dim) = absorption_depth
remove `IF (.NOT.laser_as_bc)`

2018-09-26 13:45 UTC, olegrog commented on slm_porosity/problem.inp
> +absorption_depth = 0.5
move it after `cfl_fusion_factor`

2018-09-26 14:09 UTC, olegrog commented on slm_porosity/heat_transfer.f90
> +    REAL(pr) :: radius(dim_), x_center(dim), factor_
`factor`?

2018-09-26 16:09 UTC, closed without merging